services:
  backend:
    # image: databank351/tailoring-backend:latest
    build: ../backend
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tailoringdb
    volumes:
      - pg_data:/var/lib/postgresql/data
      
volumes:
  pg_data:
